version: '3.8'

services:
  headhunter-auto-rising:
    image: catwithautism/headhunter-auto-rising:latest
    container_name: hh-auto-riser
    restart: unless-stopped
    environment:
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
      - TG_ADMIN_ID=${TG_ADMIN_ID}
      - HH_USERNAME=${HH_USERNAME}
      - HH_PASSWORD=${HH_PASSWORD}
      - HH_UPDATE_HOURS=${HH_UPDATE_HOURS}
